# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/456c0296-75d6-4eb9-994e-410e70482799";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/77bc51df-4386-4200-8128-124df37ea12a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
